apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    orgId: 1
    url: postgres_crypto:5432
    user: admin
    database: crypto_db
    secureJsonData:
      password: adminpassword
    jsonData:
      sslmode: "disable"
      postgresVersion: 1400
      timescaledb: true
    isDefault: true